# 서문 {.unnumbered}

이 책은 [`Quarto`](https://quarto.org/) 를 이용하여 한글책을 만드는 방법을 설명합니다.


##  제작 절차 {.unnumbered}

1. 먼저 `Quarto` 를 설치한다. 
  - 설치는 [`Quarto` 시작페이지](https://quarto.org/docs/get-started/)를 참고하자.

2. `Rstudio` 또는 `Vscode` 를 이용하여 `Quarto` book 프로젝트를 생성한다. 


3. `git` 환경을 구성하고 `github` 의 원격저장소에 올린다 

  - 자세한 방법은 [여기](https://docs.github.com/ko/migrations/importing-source-code/using-the-command-line-to-import-source-code/adding-locally-hosted-code-to-github)를 참조하자. 통상적으로 `github` 에 먼저 저장소를 만들고 `clone` 하는 것이 정상적 절차지만 `bookdown` 프로젝트를 초기화하기 위하여 이 방법을 사용한다.)
  - 로컬 저장소를 `github` 에 `push` 하는 경우 **personal access token**을 만들어서 password 에 입력해야 합니다. 자세한 poersonal access token 생성 과정은 [여기](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) 를 참조하세요.
  

4.  `gh-pages` branch 를 local 저장소에 만든다. 

  - 먼저 해야할 일 
    + `embed-resources: false` 로 지정해야함 
    + `main` branch 에서 모든 것을 commit 한다.
    + build 의 결과를 저장하는 폴더를 `.gitignore` 에 추가 
```
/.quarto/
/_site/
```
  - 먼저 참고할 절차는 아래와 같이 Source Branch 인 `gh-pages` branch 를 만든다.  [여기](https://quarto.org/docs/publishing/github-pages.html#publish-command)
```
git checkout --orphan gh-pages
git reset --hard # make sure you've committed changes before running this!
git commit --allow-empty -m "Initialising gh-pages branch"
git push origin gh-pages
```

5. 다시 `main` 저장소로 돌아간다.

```
git checkout main.
```

6. `Quarto` 의 `publish` 명령을 이용하여 사이트를 만든다 (command line 에서)
  
 - 주의: `-quarto.yaml` 에 있는 모든 format 을 publish 하기 때문에 모든 format 이 오류없이 실행되게 하거나 html 만 실행하도록 만든다. 
```
quarto publish gh-pages
```
  
6. 이후에는 변경된 화일을 commit 하고 publish 하면 됨 